/* Lógico_1: */

CREATE TABLE VENDOR (
    V_CODE INTEGER PRIMARY KEY,
    V_NAME VARCHAR,
    V_CONTACT VARCHAR,
    V_AREACODE VARCHAR,
    V_PHONE VARCHAR,
    V_STATE CHAR,
    V_ORDER CHAR
);

CREATE TABLE PRODUCT (
    P_CODE VARCHAR PRIMARY KEY,
    P_DESCRIPT VARCHAR,
    P_INDATE DATE,
    P_QOH INTEGER,
    P_MIN INTEGER,
    P_PRICE DECIMAL,
    P_DISCOUNT DECIMAL,
    FK_VENDOR_V_CODE INTEGER
);

CREATE TABLE LINE (
    LINE_NUMBER INTEGER PRIMARY KEY,
    LINE_UNITS INTEGER,
    LINE_PRICE DECIMAL,
    FK_INVOICE_INV_NUMBER INTEGER,
    FK_PRODUCT_P_CODE VARCHAR
);

CREATE TABLE INVOICE (
    INV_NUMBER INTEGER PRIMARY KEY,
    INV_DATE DATE,
    FK_CUSTOMER_CUS_CODE INTEGER
);

CREATE TABLE CUSTOMER (
    CUS_CODE INTEGER PRIMARY KEY,
    CUS_LNAME VARCHAR,
    CUS_FNAME VARCHAR,
    CUS_INITIAL CHAR,
    CUS_AREACODE VARCHAR,
    CUS_PHONE VARCHAR,
    CUS_BALANCE DECIMAL
);
 
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_2
    FOREIGN KEY (FK_VENDOR_V_CODE)
    REFERENCES VENDOR (V_CODE)
    ON DELETE RESTRICT;
 
ALTER TABLE LINE ADD CONSTRAINT FK_LINE_2
    FOREIGN KEY (FK_INVOICE_INV_NUMBER)
    REFERENCES INVOICE (INV_NUMBER)
    ON DELETE RESTRICT;
 
ALTER TABLE LINE ADD CONSTRAINT FK_LINE_3
    FOREIGN KEY (FK_PRODUCT_P_CODE)
    REFERENCES PRODUCT (P_CODE)
    ON DELETE RESTRICT;
 
ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_2
    FOREIGN KEY (FK_CUSTOMER_CUS_CODE)
    REFERENCES CUSTOMER (CUS_CODE)
    ON DELETE RESTRICT;