/* Lógico_1: */

CREATE TABLE CLIENTE (
    Cod_Cliente INTEGER PRIMARY KEY,
    Nome VARCHAR(50),
    Sobrenome VARCHAR(50),
    Inicial CHAR(1),
    DDD INTEGER,
    Telefone VARCHAR(15),
    Saldo DECIMAL(10,2)
);

CREATE TABLE FATURAS (
    Num_Fatura INTEGER PRIMARY KEY,
    Data_Fatura DATE,
    FK_CLIENTE_Cod_Cliente INTEGER
);

CREATE TABLE LINHAS (
    Num_Linha INTEGER PRIMARY KEY,
    Unidades INTEGER,
    Valor DECIMAL(10,2),
    FK_FATURAS_Num_Fatura INTEGER,
    FK_PRODUTOS_Cod_Produtos INTEGER
);

CREATE TABLE PRODUTOS (
    Cod_Produtos INTEGER PRIMARY KEY,
    Descrição VARCHAR(200),
    Data_Compra DATE,
    Quantidade INTEGER,
    Valor DECIMAL(10,2),
    FK_FORNECEDORES_Cod_Fornecedor INTEGER
);

CREATE TABLE FORNECEDORES (
    Cod_Fornecedor INTEGER PRIMARY KEY,
    Nome VARCHAR(100),
    Contato VARCHAR(100),
    DDD INTEGER,
    Telefone VARCHAR(15),
    Estado CHAR(2)
);
 
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_2
    FOREIGN KEY (FK_CLIENTE_Cod_Cliente)
    REFERENCES CLIENTE (Cod_Cliente)
    ON DELETE CASCADE;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_2
    FOREIGN KEY (FK_FATURAS_Num_Fatura)
    REFERENCES FATURAS (Num_Fatura)
    ON DELETE RESTRICT;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_3
    FOREIGN KEY (FK_PRODUTOS_Cod_Produtos)
    REFERENCES PRODUTOS (Cod_Produtos)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_FORNECEDORES_Cod_Fornecedor)
    REFERENCES FORNECEDORES (Cod_Fornecedor)
    ON DELETE CASCADE;